version: "3.8"
services:
  wordpress:
    image: wordpress:5.8.3-php7.4-fpm-alpine
    container_name: ${APP_NAME:?wordpress}-app
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${DATABASE_USER:?wordpress_user}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASS:?password}
      WORDPRESS_DB_NAME: ${DATABASE_NAME:?wordpress_db}
      WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX:?wp_}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:?false}
    volumes:
      - "./app/public:/var/www/html"
      - "./system/conf/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.i\
        ni:ro"
    depends_on:
      - mariadb
    networks:
      - webserver-network
      - database-network

  wp-cli:
    image: wordpress:cli-2.5.0-php7.4
    container_name: ${APP_NAME:?wordpress}-cli
    restart: unless-stopped
    volumes:
      - "./app/public:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - webserver-network
      - database-network

  nginx:
    image: nginx:1.20-alpine
    container_name: ${APP_NAME:?wordpress}-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - "php"
    volumes:
      - "./app/public:/var/www/html"
      - "./system/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./system/conf/nginx/includes/gzip.conf:/etc/nginx/includes/gzip.conf:ro"
      - "./system/conf/nginx/includes/mime-types.conf:/etc/nginx/includes/mime-\
        types.conf:ro"
      - "./system/conf/nginx/includes/restrictions.conf:/etc/nginx/includes/res\
        trictions.conf:ro"
      - "./system/logs/nginx:/var/log/nginx:rw"
    networks:
      - webserver-network

  mariadb:
    image: mariadb:10.5
    container_name: ${APP_NAME:?wordpress}-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?1234}
      MYSQL_DATABASE: ${DATABASE_NAME:?wordpress_db}
      MYSQL_USER: ${DATABASE_USER:?wordpress_user}
      MYSQL_PASSWORD: ${DATABASE_PASS:?password}
    volumes:
      - mariadb-data:/var/lib/mysql
      - "./system/conf/mysql:/etc/mysql/conf.d"
      - "./system/logs/mysql:/var/log/mysql"
    networks:
      - database-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME:?wordpress}-phpmyadmin
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - "./system/conf/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads\
        .ini"
    networks:
      - database-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${APP_NAME:?wordpress}-mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    command: [ "-storage=maildir", "-maildir-path=/maildir" ]
    volumes:
      - "./system/data/mailhog:/maildir"
    networks:
      - webserver-network

volumes:
  mariadb-data:
    name: ${APP_NAME:?wordpress}-mariadb-data

networks:
  webserver-network:
    driver: bridge
  database-network:
    driver: bridge
