version: "3.8"
services:
  wordpress:
    image: bitnami/wordpress-nginx:latest
    container_name: ${APP_NAME:?wordpress}-app
    restart: unless-stopped
    ports:
      - 80:8080
      - 443:8443
    environment:
      # Application config
      NGINX_HTTP_PORT_NUMBER: ${NGINX_HTTP_PORT:?8080}
      NGINX_HTTPS_PORT_NUMBER: ${NGINX_HTTPS_PORT:?8443}
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME:?admin}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD:?1234}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL:?admin@admin.local}
      WORDPRESS_FIRST_NAME: ${WORDPRESS_FIRST_NAME:?Admin}
      WORDPRESS_LAST_NAME: ${WORDPRESS_LAST_NAME:?User}
      WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME:?My Blog}
      WORDPRESS_DATA_TO_PERSIST: ${WORDPRESS_DATA_TO_PERSIST}
      WORDPRESS_RESET_DATA_PERMISSIONS: ${WORDPRESS_RESET_DATA_PERMISSIONS:?no}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:?wp_}
      WORDPRESS_PLUGINS: ${WORDPRESS_PLUGINS:?none}
      WORDPRESS_EXTRA_WP_CONFIG_CONTENT: |
        define( 'WP_DEBUG', ${WORDPRESS_DEBUG:?false} );
        define( 'WP_DEBUG_LOG', ${WORDPRESS_DEBUG_LOG:?false} );
        define( 'WP_DEBUG_DISPLAY', ${WORDPRESS_DEBUG_DISPLAY:?false} );
        define( 'SCRIPT_DEBUG', ${WORDPRESS_SCRIPT_DEBUG:?false} );
      WORDPRESS_ENABLE_HTTPS: ${WORDPRESS_ENABLE_HTTPS:?no}
      WORDPRESS_SKIP_BOOTSTRAP: ${WORDPRESS_SKIP_BOOTSTRAP:?no}
      WORDPRESS_AUTO_UPDATE_LEVEL: ${WORDPRESS_AUTO_UPDATE_LEVEL:?none}
      # WordPress Database
      WORDPRESS_DATABASE_HOST: ${DATABASE_HOST:?mariadb}
      WORDPRESS_DATABASE_PORT_NUMBER: ${DATABASE_PORT:?3306}
      WORDPRESS_DATABASE_NAME: ${DATABASE_NAME:?wordpress_db}
      WORDPRESS_DATABASE_USER: ${DATABASE_USER:?wordpress_user}
      WORDPRESS_DATABASE_PASSWORD: ${DATABASE_PASS:?password}
      # Database
      MYSQL_CLIENT_FLAVOR: ${DATABASE_HOST:?mariadb}
      MYSQL_CLIENT_DATABASE_HOST: ${DATABASE_HOST:?mariadb}
      MYSQL_CLIENT_DATABASE_PORT_NUMBER: ${DATABASE_PORT:?3306}
      MYSQL_CLIENT_DATABASE_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?1234}
      MYSQL_CLIENT_CREATE_DATABASE_NAME: ${DATABASE_NAME:?wordpress_db}
      MYSQL_CLIENT_CREATE_DATABASE_USER: ${DATABASE_USER:?wordpress_user}
      MYSQL_CLIENT_CREATE_DATABASE_PASSWORD: ${DATABASE_PASS:?password}
      # SMTP
      WORDPRESS_SMTP_HOST: ${SMTP_HOST}
      WORDPRESS_SMTP_PORT: ${SMTP_PORT}
      WORDPRESS_SMTP_USER: ${SMTP_USER}
      WORDPRESS_SMTP_PASSWORD: ${SMTP_PASSWORD}
      # PHP Config
      PHP_ENABLE_OPCACHE: ${PHP_ENABLE_OPCACHE:?yes}
      PHP_EXPOSE_PHP: ${PHP_EXPOSE_PHP}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:?300}
      PHP_MAX_INPUT_TIME: ${PHP_MAX_INPUT_TIME:?1000}
      PHP_MAX_INPUT_VARS: ${PHP_MAX_INPUT_VARS:?3000}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:?256M}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:?128M}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:?32M}
    volumes:
      - ./app/public:/bitnami/wordpress
    depends_on:
      - mariadb
    networks:
      - webserver-network
      - database-network

  mariadb:
    image: bitnami/mariadb:10.3
    container_name: ${APP_NAME:?wordpress}-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?1234}
      MARIADB_DATABASE: ${DATABASE_NAME:?wordpress_db}
      MARIADB_USER: ${DATABASE_USER:?wordpress_user}
      MARIADB_PASSWORD: ${DATABASE_PASS:?password}
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - database-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME:?wordpress}-phpmyadmin
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - "./system/conf/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads\
        .ini"
    networks:
      - database-network

volumes:
  mariadb_data:
    name: ${APP_NAME:?wordpress}-mariadb-data

networks:
  webserver-network:
    driver: bridge
  database-network:
    driver: bridge
