version: "3.8"
services:
  php:
    image: wordpress:${WORDPRESS_VERSION}
    container_name: ${APP_NAME:?wordpress}-php
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${DATABASE_USER:?wordpress_user}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASS:?password}
      WORDPRESS_DB_NAME: ${DATABASE_NAME:?wordpress_db}
      WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX:?wp_}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:?false}
    volumes:
      - "./app/public:/var/www/html"
      - "./system/conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    depends_on:
      - mariadb
    networks:
      - webserver-network
      - database-network

  nginx:
    image: nginx:1.20-alpine
    container_name: ${APP_NAME:?wordpress}-nginx
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    links:
      - php
    volumes:
      - "./app/public:/var/www/html"
      - "./system/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./system/conf/nginx/includes/gzip.conf:/etc/nginx/includes/gzip.conf:ro"
      - "./system/conf/nginx/includes/mime-types.conf:/etc/nginx/includes/mime-types.conf:ro"
      - "./system/conf/nginx/includes/restrictions.conf:/etc/nginx/includes/restrictions.conf:ro"
      - "./system/logs/nginx:/var/log/nginx:rw"
    networks:
      - webserver-network

  mariadb:
    image: mariadb:10.5
    container_name: ${APP_NAME:?wordpress}-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?1234}
      MYSQL_DATABASE: ${DATABASE_NAME:?wordpress_db}
      MYSQL_USER: ${DATABASE_USER:?wordpress_user}
      MYSQL_PASSWORD: ${DATABASE_PASS:?password}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - database-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME:?wordpress}-phpmyadmin
    restart: unless-stopped
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    volumes:
      - "./system/conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    networks:
      - database-network

volumes:
  mariadb-data:
    name: ${APP_NAME:?wordpress}-mariadb-data

networks:
  webserver-network:
    driver: bridge
  database-network:
    driver: bridge
